### PR TITLE
Allow playbooks to be run on RedHat 7

### PR DESCRIPTION
**Pull request by danragnar**
Simple link the vars file for CentOS, works nicely on RHEL 7 at least, not tested on RHEL 8.

### CODE REVIEW

**Comment by tadeboro** [comment]
Thanks for your contribution, @danragnar. But before we can merge this, we will need to add RHEL 7 platform to https://github.com/sensu/sensu-go-ansible/blob/master/tests/integration/molecule/role_install_default/molecule.yml

**Comment by danragnar** [comment]
I'm looking into it. Should I submit a PR [here](https://github.com/xlab-si/sensu-go-test-images) for the build of a RHEL7 based docker image?

**Comment by tadeboro** [comment]
> Should I submit a PR [here](https://github.com/xlab-si/sensu-go-test-images) for the build of a RHEL7 based docker image?

That would be completelly awesome!

**Comment by danragnar** [comment]
Here you go: https://github.com/xlab-si/sensu-go-test-images/pull/1

**Comment by danragnar** [comment]
You too, cheers!

**Pull request merged**
